### ISSUE TITLE
integration with https://pypi.org/project/typed-settings/

### ISSUE THREAD

**Issue by rbonthond** [BrianPugh/cyclopts#97]
have you seen https://pypi.org/project/typed-settings/? would it be interesting to combine this with cycleopt to deal with configuration files?

**Comment by BrianPugh** [comment]
Related discussion: #87 

I'm not too familiar with `typed-settings`, I'll need to play around with it. I imagine it might be a good solution with a similar meta-app as described in #87 . Such a solution is preferable if it works!

**Comment by BrianPugh** [comment]
The open PR (which I'm hoping to merge soon) #165 is also relevant. Between this and the feature described in #171, I think it covers most of the core functionality mentioned in typed-settings without explicitly using typed-settings.

All that said, I'd be more than happy to merge a typed-setting specific class `cyclopts.config.TypedSetting` PR. I don't feel confident in tackling it myself since I don't have much experience with the library.

**Comment by rbonthond** [comment]
new configuration setup looks good, I'll look into that

**Comment by BrianPugh** [comment]
Just a heads up: in cyclopts v3.0.0 the configuration system API (i.e. the config function signature) is going to change. So if you define a custom config function, it'll need to be tweaked once v3.0.0 is available. I should have a release candidate of v3.0.0 within a month; I'll let you know when its out in case you'd like to give it a try/give feedback!
